Account for unmerged files when committing.
The `git checkout --force` command leaves unmerged files alone rather
than removing their modifications. This change adds `git reset --hard`
to ensure a clean initial working directory.

This change also adds distinct failure messages for the case where the
patch file yields no modifications (index is empty) as compared to when
the commit fails (previously, due to unmerged changes).

diff --git a/bin/prepare-workspace b/bin/prepare-workspace
--- a/bin/prepare-workspace
+++ b/bin/prepare-workspace
@@ -61,6 +61,7 @@ function parse_options () {
 
 function clean_and_checkout () {
    git clean --quiet -fd --exclude .hhvm --exclude .class-index
+   git reset --hard HEAD
    git checkout --quiet --force origin/master
    debug "head is:" $(git_commit_hash)
 }
@@ -104,13 +105,18 @@ function apply_patch () {
             fi
            done
    fi
-   debug "apply and commit patchfile"
+   debug "apply patchfile"
    git apply -3 --index "${OPTIONS['patchfile']}" 2> /dev/null \
       || fail 'Patchfile did not apply cleanly.'
 
+   if git diff-index --quiet HEAD; then
+      fail 'Patchfile did not yield any modifications.'
+   fi
+
+   debug "commit patchfile"
    git -c 'user.name=hussar' -c 'user.email=noreply@localhost' \
       commit --quiet -m 'Apply patchfile.' &> /dev/null        \
-      || fail 'Patchfile did not yield any modifications.'
+      || fail 'Commit failed.'
 
    debug "head is:" $(git_commit_hash)
 }
